src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=AnimalRepository::class)
 * @Vich\Uploadable
 */
class Animal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     * @Groups("api_animals_list")
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     */
    private $imageName;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="integer")
     * @Groups("api_animals_list")
     */
    private $age;

    /**
     * @ORM\Column(type="boolean")
     * @Groups("api_animals_list")
     */
    private $child_compatibility;

    /**
     * @ORM\Column(type="boolean")
     * @Groups("api_animals_list")
     */
    private $other_animal_compatibility;

    /**
     * @ORM\Column(type="boolean")
     * @Groups("api_animals_list")
     */
    private $garden_needed;

    /**
     * @ORM\Column(type="smallint")
     * @Groups("api_animals_list")
     */
    private $status;

    /**
     * @ORM\Column(type="text")
     * @Groups("api_animals_list")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Department::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("api_animals_list")
     */
    private $department;

    /**
     * @ORM\ManyToOne(targetEntity=Species::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("api_animals_list")
     */
    private $species;

    /**
     * @ORM\ManyToOne(targetEntity=Association::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("api_animals_list")
     */
    private $association;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="favoris")
     */
    private $favoris;

    public function __construct()
    {
        $this->favoris = new ArrayCollection();
    }


     /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getChildCompatibility(): ?bool
    {
        return $this->child_compatibility;
    }

    public function setChildCompatibility(bool $child_compatibility): self
    {
        $this->child_compatibility = $child_compatibility;

        return $this;
    }

    public function getOtherAnimalCompatibility(): ?bool
    {
        return $this->other_animal_compatibility;
    }

    public function setOtherAnimalCompatibility(bool $other_animal_compatibility): self
    {
        $this->other_animal_compatibility = $other_animal_compatibility;

        return $this;
    }

    public function getGardenNeeded(): ?bool
    {
        return $this->garden_needed;
    }

    public function setGardenNeeded(bool $garden_needed): self
    {
        $this->garden_needed = $garden_needed;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getSpecies(): ?Species
    {
        return $this->species;
    }

    public function setSpecies(?Species $species): self
    {
        $this->species = $species;

        return $this;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): self
    {
        $this->association = $association;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(User $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris[] = $favori;
        }

        return $this;
    }

    public function removeFavori(User $favori): self
    {
        $this->favoris->removeElement($favori);

        return $this;
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/animal")
 */
class AnimalController extends AbstractController
{
    /**
     * @Route("/", name="app_animal_index", methods={"GET"})
     */
    public function index(AnimalRepository $animalRepository): Response
    {
        return $this->render('animal/index.html.twig', [
            'animals' => $animalRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_animal_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AnimalRepository $animalRepository): Response
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('animal/new.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_show", methods={"GET"})
     */
    public function show(Animal $animal): Response
    {
        return $this->render('animal/show.html.twig', [
            'animal' => $animal,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_animal_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('animal/edit.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_delete", methods={"POST"})
     */
    public function delete(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$animal->getId(), $request->request->get('_token'))) {
            $animalRepository->remove($animal);
        }

        return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Api/AnimalController.php
<?php

namespace App\Controller\Api;

use App\Entity\Animal;
use App\Entity\FavoriteAnimalUser;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use App\Repository\FavoriteAnimalUserRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Serializer\Exception\NotEncodableValueException;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Serializer;

class AnimalController extends AbstractController
{

    /**
     * @Route("/api/animal/form", name="app_api_animal_test", methods={"POST","GET"})
     */
    public function AnimalResult(Request $request, AnimalRepository $animalRepository)
    {
        // Récupérer le contenu JSON
        $jsonContent = $request->getContent();
    
        $parsed_json = json_decode($jsonContent);
        //dump($parsed_json);

        $gender = $parsed_json->gender;   
        if ($gender === 0) {
            $genderMin = 0;
            $genderMax = 0;
        }
        if ($gender === 1) {
            $genderMin = 1;
            $genderMax = 1;
        }
        if ($gender === 2) {
            $genderMin = 0;
            $genderMax = 1;
        }
        
        $species = $parsed_json->species; 
// Todo vérouiller le choix des ages
        $age = $parsed_json->age;    
        if ($age === 0) {
            $ageMin = 0;
            $ageMax = 1;
        }
        if ($age === 1) {
            $ageMin = 1;
            $ageMax = 5;
        }
        if ($age === 2) {
            $ageMin = 6;
            $ageMax = 10;
        }
        if ($age === 3) {
            $ageMin = 11;
            $ageMax = 30;
        }  
        if ($age === 4) {
            $ageMin = 0;
            $ageMax = 30;
        }

        $child_compatibility = $parsed_json->childCompatibility;    
        $other_animal_compatibility = $parsed_json->other_animal_compatibility;    
        $garden_needed = $parsed_json->garden_needed;
        $department = $parsed_json->department; 
        $status = $parsed_json->status;
        
        // Envoyer les variables dans une méthode qui executera la requete SQL et les stocker dans une variable
        $results = $animalRepository->findAnimalsFromSearchForm($genderMin, $genderMax,$species, $ageMin, $ageMax, $child_compatibility, $other_animal_compatibility, $garden_needed, $status, $department);
       
        // Envoyer la variable contenant les résultats en json pour le Front
        return $this->json($results, Response::HTTP_OK,[], ['groups' => 'api_animals_list']);

    }

    /**
     * @Route("/api/animal", name="app_api_animal_list", methods={"GET"})
     */
    public function animalList(AnimalRepository $animalRepository): Response
    {
        $animals = $animalRepository->findAll();
        //dump($animals);

        return $this->json($animals, Response::HTTP_OK,[],['groups' => 'api_animals_list']);
    }

    /**
     * @Route("/api/animal/caroussel", name="app_api_animal_caroussel", methods={"GET"})
     */
    public function animalCaroussel(AnimalRepository $animalRepository): Response
    {
        // $animalIdMin = $animalRepository->findItemsMin();
        // $animalIdMax = $animalRepository->findItemsMax();
        // // dump($animalIdMin);
        // dd($animalIdMax);



        $animalsCount = $animalRepository->findAnimalsForCaroussel();

        $keys = array_rand($animalsCount,10);

        $results = [];
        foreach ($keys as $key) {
            $results[] = $animalsCount[$key];
        }

        return $this->json($results, Response::HTTP_OK);
    }

    /**
     * Function for adding animals in favorites
     * @route("/api/animal/addFavorites/{id}", name="app_api_animal_addFavorites", methods={"POST"})
     *
     * @return Response
     */
    public function addFavorites(Request $request, ManagerRegistry $doctrine, SerializerInterface $serializer, Animal $animal, UserRepository $userRepository) :Response
    {
        // vérifier si le user est connecté quand il clique sur le bouton d'ajout favori
        
        // Recevoir le json avec le user, le décoder et le mettre en variable.
        $jsonContent = $request->getContent();
        $parsed_json = json_decode($jsonContent);
        $userConnected = $parsed_json->user_id;
        
        // Trouver le user correspondant à l'id reçu dans le json
        $user = $userRepository->find($userConnected);
       
        // Ajouter BDD l'animal dans les favoris du user
        $animal->addFavori($user);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($animal);
        $entityManager->flush();
        
        // todo Rester sur la même page et changer icone de favori
        return $this->json($userConnected);

    }

     /**
     * Function for remove animals from favorites
     * @route("/api/animal/removeFavorites/{id}", name="app_api_animal_removeFavorites", methods={"POST"})
     *
     * @return Response
     */
    public function removeFavorites(Request $request, ManagerRegistry $doctrine, SerializerInterface $serializer, Animal $animal, UserRepository $userRepository) :Response
    {
        // vérifier si le user est connecté quand il clique sur le bouton d'ajout favori
        
        // Recevoir le json avec le user, le décoder et le mettre en variable.
        $jsonContent = $request->getContent();
        $parsed_json = json_decode($jsonContent);
        $userConnected = $parsed_json->user_id;
        
        // Trouver le user correspondant à l'id reçu dans le json
        $user = $userRepository->find($userConnected);
       
        // Ajouter BDD l'animal dans les favoris du user
        $animal->removeFavori($user);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($animal);
        $entityManager->flush();
        
        // todo Rester sur la même page et changer icone de favori
        return $this->json($userConnected);

    }
}

templates/back/animal/_delete_form.html.twig
<form method="post" action="{{ path('app_animal_delete', {'id': animal.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer ceci?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ animal.id) }}">
    <button class="btn btn-danger"><i class="bi bi-trash"></i> Supprimer</button>
</form>

templates/back/animal/_form.html.twig
{{ form_start(form) }}
    <div class="row">
    {{ form_row(form.name) }}
    <div class="col-6">
    </div>
    </div>

    <div class="row">
    <div class="col-4">
    {{ form_row(form.species) }}
    </div>
    <div class="col-4">
    {{ form_row(form.gender) }}
    </div>
    <div class="col-4">
    {{ form_row(form.age) }}
    </div>
    </div>
    {{ form_row(form.description) }}
    {{ form_row(form.imageFile) }}
    
    <div class="row">
    <div class="col-4">
    {{ form_row(form.child_compatibility) }}
    </div>
    <div class="col-4">
    {{ form_row(form.other_animal_compatibility) }}
    </div>
    <div class="col-4">
    {{ form_row(form.garden_needed) }}
    </div>
    </div>
    {{ form_row(form.status) }}
    <div class="row">
    <div class="col-6">
    {{ form_row(form.department) }}
    </div>
    <div class="col-6">
    {{ form_row(form.association) }}
    </div>
    </div>

  <button class="btn btn-success mb-3">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/back/animal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la fiche animal{% endblock %}

{% block body %}
<div class="container w-50 mx-auto">
    <h1>Edition la fiche animal
        <a class="btn btn-return float-end" href="{{ path('app_animal_index') }}">Retour à la liste</a>
    </h1>

    {{ include('back/animal/_form.html.twig', {'button_label': 'Mettre à jour'}) }}


    {{ include('back/animal/_delete_form.html.twig') }}

</div>
{% endblock %}

templates/back/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal index{% endblock %}

{% block body %}

<div class="container">
    <h1>Liste des animaux</h1>

    <a class="btn btn-info ajouter" href="{{ path('app_animal_new') }}"><i class="bi bi-plus-circle"></i> Ajouter</a>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Photo</th>
                <th>Nom</th>
                <th>Espèce</th>
                {# <th>Genre</th> #}
                <th>Age</th>
                {# <th>Sociable avec les enfants ?</th>
                <th>Sociable avec autres animaux ?</th>
                <th>Besoin d'un jardin ?</th> #}
                <th>Status</th>
                <th>Description</th>
                <th>Association</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for animal in animals %}
            <tr>
                <td>{{ animal.id }}</td>
                <td><img class="img_backoffice_index" src={% if 'http' in animal.imageName %}"{{ animal.imageName }}"{% else %}"{{ asset('images/animaux/')}}{{ animal.imageName }}"{% endif %}></td>
                <td>{{ animal.name }}</td>
                <td>{{ animal.species.name }}</td>
                {# <td>{% if animal.gender == '0' %} Femelle{% elseif animal.gender == '1' %} Male{% endif %}</td> #}
                <td>{{ animal.age }}</td>
                {# <td>{{ animal.childCompatibility ? 'Oui' : 'Non' }}</td>
                <td>{{ animal.otherAnimalCompatibility ? 'Oui' : 'Non' }}</td>
                <td>{{ animal.gardenNeeded ? 'Oui' : 'Non' }}</td> #}
                <td>{% if animal.status == '0' %} Disponible{% elseif animal.status == '1' %} Resa en cours{% elseif animal.status == '2' %} Indisponible{% elseif animal.status == '3' %} Adopté{% endif %}</td>
                <td>{{ animal.description }}</td>
                <td>{{ animal.association.name }}</td>
                <td><a class="btn btn-sm btn-warning" href="{{ path('app_animal_show', {'id': animal.id}) }}"><i class="bi bi-zoom-in"></i></a></td>
                <td><a class="btn btn-sm btn-success" href="{{ path('app_animal_edit', {'id': animal.id}) }}"><i class="bi bi-pencil"></i></a></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div>
{% endblock %}

templates/back/animal/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Animal{% endblock %}

{% block body %}
<div class="container w-50 mx-auto">
    <h1>Ajout d'un animal</h1>

    {{ include('back/animal/_form.html.twig') }}

    <a class="btn btn-secondary float-end mb-3" href="{{ path('app_animal_index') }}">Retour à la liste</a>
</div>
{% endblock %}

templates/back/animal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
<div class="container">
<div class="d-flex p-2 bd-highlight" style="margin-bottom: 2rem">

    <div class="picture">
    <h1>Fiche de {{animal.name}}</h1>

        <img class="img_backoffice_show" style="margin: 2rem 2rem 2rem 0" src={% if 'http' in animal.imageName %}"{{ animal.imageName }}"{% else %}"{{ asset('images/animaux/')}}{{ animal.imageName }}"{% endif %}>
         
        <h3>Description</h3>
        <span style="padding-right: 5rem">{{ animal.description }}</span>
    </div>

    <table class="table" style="margin-top: 4.5rem">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ animal.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ animal.name }}</td>
            </tr>
            <tr>
                <th>Espèce animale</th>
                <td>{{ animal.species.name }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{% if animal.gender == '0' %} Femelle{% elseif animal.gender == '1' %} Male{% endif %}</td>
            </tr>
            {# <tr>
                <th>Photo</th>
                <td><img class="img_backoffice_show" src="{{ asset('images/animaux/')}}{{ animal.imageName }}"></td>
            </tr> #}
            <tr>
                <th>Age</th>
                <td>{{ animal.age }}</td>
            </tr>
            <tr>
                <th>Sociable avec les enfants ?</th>
                <td>{{ animal.childCompatibility ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>Sociable avec autres animaux ?</th>
                <td>{{ animal.otherAnimalCompatibility ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>Besoin d'un jardin ?</th>
                <td>{{ animal.gardenNeeded ? 'Oui' : 'Non'}}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{% if animal.status == '0' %} Disponible{% elseif animal.status == '1' %} Resa en cours{% elseif animal.status == '2' %} Indisponible{% elseif animal.status == '3' %} Adopté{% endif %}</td>
            </tr>
            {# <tr>
                <th>Description</th>
                <td>{{ animal.description }}</td>
            </tr> #}
                        <tr>
                <th>Association</th>
                <td>{{ animal.association.name }}</td>
            </tr>
                        <tr>
                <th>Département d'accueil</th>
                <td>{{ animal.department.name }}</td>
            </tr>

        </tbody>
    </table>
    </div>

    <div class="show_buttons">
        <a class="btn btn-warning_show" style="margin-left: 0.8rem" href="{{ path('app_animal_edit', {'id': animal.id}) }}">Mettre à jour</a>
        <p>{{ include('back/animal/_delete_form.html.twig') }}</p>
        <a class="btn btn-secondary" href="{{ path('app_animal_index') }}">Retour à la liste</a>
    </div>

</div>
{% endblock %}