src/Entity/Association.php
<?php

namespace App\Entity;

use App\Repository\AssociationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AssociationRepository::class)
 */
class Association
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Groups("api_associations_list")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     */
    private $siren;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity=Animal::class, mappedBy="association")
     */
    private $animals;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="association")
     */
    private $users;

    public function __construct()
    {
        $this->animals = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSiren(): ?string
    {
        return $this->siren;
    }

    public function setSiren(string $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return Collection<int, Animal>
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    public function addAnimal(Animal $animal): self
    {
        if (!$this->animals->contains($animal)) {
            $this->animals[] = $animal;
            $animal->setAssociation($this);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): self
    {
        if ($this->animals->removeElement($animal)) {
            // set the owning side to null (unless already changed)
            if ($animal->getAssociation() === $this) {
                $animal->setAssociation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setAssociation($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getAssociation() === $this) {
                $user->setAssociation(null);
            }
        }

        return $this;
    }
}

src/Form/AssociationType.php
<?php

namespace App\Form;

use App\Entity\Association;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AssociationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'label' => 'Nom de l\'association',
            ])
            ->add('description', null, [
                'label' => 'Description',
            ])
            ->add('siren', null, [
                'label' => 'Numéro de SIREN',
            ])
            ->add('street', null, [
                'label' => 'Numéro et voie',
            ])
            ->add('zip_code', null, [
                'label' => 'Code postal',
            ])
            ->add('city', null, [
                'label' => 'Ville',
            ])
            ->add('phone_number', null, [
                'label' => 'Téléphone',
                // TODO - Peut-être ajouter un champs pour préciser "facultatif"
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
            ])
            ->add('active', null, [
                'label' => 'Active ?',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Association::class,
        ]);
    }
}

src/Controller/Api/AssociationController.php
<?php

namespace App\Controller\Api;

use App\Repository\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AssociationController extends AbstractController
{
    /**
     * @Route("/api/association", name="app_api_association")
     */
    public function associationList(AssociationRepository $associationRepository): Response
    {
        $associations = $associationRepository->findAll();

        return $this->json($associations, Response::HTTP_OK,[], ['groups' => 'api_associations_list']);
    }
}

src/Controller/Back/AnimalController.php
<?php

namespace App\Controller\Back;

use App\Entity\Animal;
use App\Entity\Association;
use App\Entity\User;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/animal")
 * @IsGranted("ROLE_ASSOCIATION")
 */
class AnimalController extends AbstractController
{
    /**
     * @Route("/", name="app_animal_index", methods={"GET"})
     */
    public function index(AnimalRepository $animalRepository, UserInterface $user): Response
    {
        
        /** @var User $user */
        if (!$this->isGranted('ROLE_ADMIN')) {
            // $test = $user->get->association;
            // dd($test);
            return $this->render('back/animal/index.html.twig', [
            'animals' => $animalRepository->findByAssociation($user->getAssociation())
        ]);
        }

        return $this->render('back/animal/index.html.twig', [
            'animals' => $animalRepository->findAll(),
        ]);
    
    }

    /**
     * @Route("/new", name="app_animal_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AnimalRepository $animalRepository): Response
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);

            return $this->redirectToRoute('app_animal_show', ['id' => $animal->getId()], Response::HTTP_SEE_OTHER);
            //return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/animal/new.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_show", methods={"GET"})
     */
    public function show(Animal $animal): Response
    {
        //dd($animal->getGardenNeeded());
        return $this->render('back/animal/show.html.twig', [
            'animal' => $animal,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_animal_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/animal/edit.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_delete", methods={"POST"})
     */
    public function delete(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$animal->getId(), $request->request->get('_token'))) {
            $animalRepository->remove($animal);
        }

        return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/AssociationController.php
<?php

namespace App\Controller\Back;

use App\Entity\Association;
use App\Form\AssociationType;
use App\Repository\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/association")
 * @IsGranted("ROLE_ADMIN")
 */
class AssociationController extends AbstractController
{
    /**
     * @Route("/", name="app_association_index", methods={"GET"})
     */
    public function index(AssociationRepository $associationRepository): Response
    {
        return $this->render('back/association/index.html.twig', [
            'associations' => $associationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_association_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AssociationRepository $associationRepository): Response
    {
        $association = new Association();
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $associationRepository->add($association);
            return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/association/new.html.twig', [
            'association' => $association,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_association_show", methods={"GET"})
     */
    public function show(Association $association): Response
    {
        return $this->render('back/association/show.html.twig', [
            'association' => $association,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_association_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Association $association, AssociationRepository $associationRepository): Response
    {
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $associationRepository->add($association);
            return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/association/edit.html.twig', [
            'association' => $association,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_association_delete", methods={"POST"})
     */
    public function delete(Request $request, Association $association, AssociationRepository $associationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$association->getId(), $request->request->get('_token'))) {
            $associationRepository->remove($association);
        }

        return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/SpeciesController.php
<?php

namespace App\Controller\Back;

use App\Entity\Species;
use App\Form\SpeciesType;
use App\Repository\SpeciesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/species")
 * @IsGranted("ROLE_ADMIN")
 */
class SpeciesController extends AbstractController
{
    /**
     * @Route("/", name="app_species_index", methods={"GET"})
     */
    public function index(SpeciesRepository $speciesRepository): Response
    {
        return $this->render('back/species/index.html.twig', [
            'species' => $speciesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_species_new", methods={"GET", "POST"})
     */
    public function new(Request $request, SpeciesRepository $speciesRepository): Response
    {
        $species = new Species();
        $form = $this->createForm(SpeciesType::class, $species);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $speciesRepository->add($species);
            return $this->redirectToRoute('app_species_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/species/new.html.twig', [
            'species' => $species,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_species_show", methods={"GET"})
     */
    public function show(Species $species): Response
    {
        return $this->render('back/species/show.html.twig', [
            'species' => $species,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_species_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Species $species, SpeciesRepository $speciesRepository): Response
    {
        $form = $this->createForm(SpeciesType::class, $species);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $speciesRepository->add($species);
            return $this->redirectToRoute('app_species_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/species/edit.html.twig', [
            'species' => $species,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_species_delete", methods={"POST"})
     */
    public function delete(Request $request, Species $species, SpeciesRepository $speciesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$species->getId(), $request->request->get('_token'))) {
            $speciesRepository->remove($species);
        }

        return $this->redirectToRoute('app_species_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back/association/_delete_form.html.twig
<form method="post" action="{{ path('app_association_delete', {'id': association.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer ceci?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ association.id) }}">
    <button class="btn btn-danger"> <i class="bi bi-trash"></i> Supprimer</button>
</form>

templates/back/association/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer la fiche de l'Association{% endblock %}

{% block body %}
<div class="container  w-50 mx-auto">
    <h1>Editer la fiche de l'Association
        <a class="btn btn-return float-end" href="{{ path('app_association_index') }}">Retour à la liste</a>
    </h1>

    {{ include('back/association/_form.html.twig', {'button_label': 'Mettre à jour'}) }}


    {{ include('back/association/_delete_form.html.twig') }}
    
</div>
{% endblock %}

templates/back/association/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Associations{% endblock %}

{% block body %}
<div class="container">
    <h1>Liste des Associations</h1>

    <a class="btn btn-info ajouter" href="{{ path('app_association_new') }}"><i class="bi bi-plus-circle"></i> Ajouter</a>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                {# <th>Description</th>
                <th>Siren</th> #}
                <th>Adresse</th>
                <th>Code postal</th>
                <th>Ville</th>
                <th>Numéro de téléphone</th>
                <th>Email</th>
                <th>Statut</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for association in associations %}
            <tr>
                <td>{{ association.id }}</td>
                <td>{{ association.name }}</td>
                {# <td>{{ association.description }}</td> #}
                {# <td>{{ association.siren }}</td> #}
                <td>{{ association.street }}</td>
                <td>{{ association.zipCode }}</td>
                <td>{{ association.city }}</td>
                <td>{{ association.phoneNumber }}</td>
                <td>{{ association.email }}</td>
                <td>{{ association.active ? 'Actif' : 'Inactif' }}</td>
                <td><a  class="btn btn-sm btn-warning" href="{{ path('app_association_show', {'id': association.id}) }}"><i class="bi bi-zoom-in"></i></a></td>
                <td><a class="btn btn-sm btn-success" href="{{ path('app_association_edit', {'id': association.id}) }}"><i class="bi bi-pencil"></i></a></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div>
{% endblock %}

templates/back/association/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Association{% endblock %}

{% block body %}
<div class="container w-50 mx-auto">
    <h1>Ajout d'une association</h1>

    {{ include('back/association/_form.html.twig') }}

    <a class="btn btn-secondary float-end mb-3" href="{{ path('app_association_index') }}">Retour à la liste</a>
</div>
{% endblock %}

templates/back/association/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association{% endblock %}

{% block body %}
<div class="container">

    <h1>Fiche de {{association.name}}</h1>

    <table class="table" style="margin: 2rem 0 2rem">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ association.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ association.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ association.description }}</td>
            </tr>
            <tr>
                <th>Siren</th>
                <td>{{ association.siren }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ association.street }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ association.zipCode }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ association.city }}</td>
            </tr>
            <tr>
                <th>Numéro de téléphone</th>
                <td>{{ association.phoneNumber }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ association.email }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ association.active ? 'Actif' : 'Inactif'  }}</td>
            </tr>
        </tbody>
    </table>

    <div class="show_buttons">
        <a class="btn btn-warning_show" style="margin-left: 0.8rem"  href="{{ path('app_association_edit', {'id': association.id}) }}">Mettre à jour</a>
        <p>{{ include('back/association/_delete_form.html.twig') }}</p>
        <a class="btn btn-secondary" href="{{ path('app_association_index') }}">Retour à la liste</a>
    </div>

</div>
{% endblock %}